### ISSUE TITLE
Font file doesn't exist

### ISSUE THREAD

**Issue by ptlCoder** [PrideChung/FontAwesomeKit#105]
Font file doesn't exist

**Comment by divide-by-fish** [comment]
I just had this issue - in my case it happens when using FAKOcticons. 

A close look at the FAKOcticons.m shows that as of v2.2.1, it's **the only** resource to be loaded **_from mainBundle_**, not bundleForClass.  [see FAKOcticons.m -> registerIconFontWithURL](https://github.com/PrideChung/FontAwesomeKit/blob/ed5eb02f4bcf76e218bb1c966c551a7b5240b6b4/FontAwesomeKit/FAKOcticons.m#L10)

To solve this, for now, I copied resource "FontAwsomeKit/Octicons/Resources/octicons.ttf" to my main bundle, and it worked.
